//@depends UI/Bootstrap.js
//@depends UI/Bootstrap.Dropdown.js
//@depends UI/Bootstrap.Tooltip.js
//@depends UI/Bootstrap.Popover.js
//@depends UI/Bootstrap.Popup.js
//@depends UI/CSSEvents.js
//@depends UI/Delegator.BS.ShowPopup.js
//@depends Behaviors/Behavior.BS.Alert.js
//@depends Behaviors/Behavior.BS.Dropdown.js
//@depends Behaviors/Behavior.BS.FormValidator.js
//@depends Behaviors/Behavior.BS.Popover.js
//@depends Behaviors/Behavior.BS.Popup.js
//@depends Behaviors/Behavior.BS.Popup.FormRequest.js
//@depends Behaviors/Behavior.BS.Tabs.js
//@depends Behaviors/Behavior.BS.Tooltip.js