CREATE TABLE `#__opensocial_profiles` (
  `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `socialengine_actor_id` bigint(11) NOT NULL,
  `honorific_prefix` varchar(250) DEFAULT NULL,
  `honorific_suffix` varchar(250) DEFAULT NULL,
  `build` varchar(250) DEFAULT NULL,
  `eye_color` varchar(250) DEFAULT NULL,
  `hair_color` varchar(250) DEFAULT NULL,
  `height` varchar(250) DEFAULT NULL,
  `weight` varchar(250) DEFAULT NULL,
  `activities` text,
  `books` text,
  `cars` text,
  `children` varchar(255) DEFAULT NULL,
  `date_of_birth` varchar(10) DEFAULT NULL,
  `drinker` varchar(255) DEFAULT NULL,
  `ethnicity` varchar(100) DEFAULT NULL,
  `fashion` varchar(100) DEFAULT NULL,
  `food` text,
  `happiest_when` varchar(255) DEFAULT NULL,
  `heroes` text,
  `humor` text,
  `interests` text,
  `job_interests` varchar(255) DEFAULT NULL,
  `living_arrangement` varchar(255) DEFAULT NULL,
  `looking_for` varchar(255) DEFAULT NULL,
  `movies` text,
  `music` text,
  `nickname` varchar(255) DEFAULT NULL,
  `pets` varchar(100) DEFAULT NULL,
  `political_views` varchar(255) DEFAULT NULL,
  `profile_song` varchar(255) DEFAULT NULL,
  `profile_url` varchar(255) DEFAULT NULL,
  `profile_video` varchar(255) DEFAULT NULL,
  `quotes` text,
  `relationship_status` varchar(255) DEFAULT NULL,
  `religion` varchar(255) DEFAULT NULL,
  `romance` varchar(255) DEFAULT NULL,
  `scared_of` varchar(255) DEFAULT NULL,
  `sexual_orientation` varchar(255) DEFAULT NULL,
  `smoker` varchar(255) DEFAULT NULL,
  `sports` text,
  `turn_offs` text,
  `turn_ons` text,
  `tv_shows` text,
  `urls` text,
  PRIMARY KEY (`id`),
  KEY `build` (`build`),
  KEY `eye_color` (`eye_color`),
  KEY `hair_color` (`hair_color`),
  KEY `ethnicity` (`ethnicity`),
  KEY `religion` (`religion`),
  KEY `drinker` (`drinker`),
  KEY `smoker` (`smoker`),
  KEY `political_views` (`political_views`),
  KEY `sexual_orientation` (`sexual_orientation`),
  KEY `relationship_status` (`relationship_status`),
  KEY `looking_for` (`looking_for`),
  KEY `socialengine_actor_id` (`socialengine_actor_id`)
) ENGINE=InnoDB;